### ISSUE TITLE
爱心屋问题

### ISSUE THREAD

**Issue by lengyijun** [Eskibear/home#1]
学长你好，看了你的爱心屋模拟登陆，发现能运行是能运行，就是有时会先失败几次。这是什么原因？

**Comment by Eskibear** [comment]
大概是`image_to_string`这里识别jaccount验证码的时候认错了吧，然后登陆失败了。

**Comment by lengyijun** [comment]
还有个问题，imageField.x 这个参数你填的是53，是静态的，
这个参数是什么意义
好像是动态的，并不是固定的。。。

**Comment by Eskibear** [comment]
提交表单的时候鼠标点在按钮图片上的位置

**Comment by lengyijun** [comment]
试了一下，很有道理。
这两个参数加上去有什么用吗？统计点击习惯？

**Comment by Eskibear** [comment]
也可以吧。很多地方的表单提交都用了它，想必还是有点用的。你可以网上查一下，或者找个做web的问问，我不太清楚。
